### ISSUE TITLE
compile 'com.auth0.android:lock-googleplus:+' in gradle cause exception

### ISSUE THREAD

**Issue by tal952** [auth0/react-native-lock-android#12]
```
compile 'com.auth0.android:lock-googleplus:+' 
```
in gradel cause exception:
```
Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzrn.class
```

i am upgraded to react-native .22

**Comment by nikolaseu** [comment]
Are you using google play services? If that's the case then seems like you're mixing versions.  [Lock-GooglePlus](https://github.com/auth0/Lock-GooglePlus.Android) includes `com.google.android.gms:play-services-plus:8.3.0`

**Comment by tal952** [comment]
thanks for quick respond!
i think you're right, i'm using  react-native-google-analytics-bridge and he has got dependency to 
```
compile 'com.google.android.gms:play-services-analytics:8.+'
```
it must be it.
